config/routes.rb
Blog::Application.routes.draw do

  resources :posts
  resources :fxtrends

  root to: 'posts#index', as: "posts"

  
end

app/models/fxtrend.rb
class Fxtrend < ActiveRecord::Base
	attr_accessible :pamm, :date, :percent, :kind
end

app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :title, :annot, :description, :enable
	validates :title, :annot, :description, :presence => true 

	after_create {puts "created"}
	after_destroy {puts "destroyed"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def render_404
  	render file: 'public/404.html', status: 404 
  end  
  def render_403
  	render file: 'public/403.html', status: 403
  end
end

app/controllers/fxtrends_controller.rb
# encoding: utf-8

class FxtrendsController < ApplicationController

	def index
		@fxtrends = Fxtrend.all
	end

	def new
		@fxtrend = Fxtrend.new
	end

	def create

		#require 'rubygems'
		require 'mechanize'
		require "date"
		@fxtrend = params[:fxtrend]
		pamm = @fxtrend[:pamm]
		puts YAML::dump(@fxtrend[:pamm])

		agent = Mechanize.new
		page = agent.get('http://fx-trend.com/pamm/'+@fxtrend[:pamm]+'/')
		pamm_info = ''
		firstArray = []
		tmpArray = []
		flagB = false 
		page.search("table.my_accounts_table tr td").each do |td|

			if td.text.empty?
				next
			end

			# Проверям флаг flagB. Если он включен - ищем подстроки процентов
			if flagB
				# ~ Определяем строки вида "-26.75%" | "26.75%"
				md = /^([0-9.-]+)%$/.match td.text.to_s 
				if md.nil?
					next
				end	
				# Нашли значение процента. Сохраним в массив
				tmpArray << md[1].to_f
				firstArray << tmpArray
				tmpArray =[]
				flagB = false
			else
			
			end

			# ~ Определяем строки вида "Декабрь 2011" ~

			md = /^([А-Яа-я]+)\s([0-9]{4,})$/.match td.text.to_s 
			if md.nil?
				next
			end
			unless md[1].empty? && md[2].empty?
				# есть совпадение. Установим флаг, преобразуем месяц и год в метку времени
				flagB = true
				month = md[1].to_s
				year = md[2].to_i
				case month
				when 'Январь'
				  month = 1
				when 'Февраль'
				  month = 2
				when 'Март'
				  month = 3
				when 'Апрель'
				  month = 4
				when 'Май'
				  month = 5
				when 'Июнь'
				  month = 6
				when 'Июль'
				  month = 7
				when 'Август'
				  month = 8
				when 'Сентябрь'
				  month = 9
				when 'Октябрь'
				  month = 10
				when 'Ноябрь'
				  month = 11
				when 'Декабрь'
				  month = 12
				else
				  month = nil
				end
				
				date = Date.new(year,month)
				tmpArray << date			
			end
		end

		firstArray.each do |el|
			@fxtrend = Fxtrend.new(pamm: pamm, date: el[0], percent: el[1], kind: 'month')
			@fxtrend.save!	
		end

		return render :text => YAML::dump(firstArray)
		redirect_to fxtrends_path(id: pamm)

		#@post = Post.new(params[:post])
		#puts YAML::dump("asdasdas")
		#@post.save!
		#@post = Post.create(params[:post])

		#if @post.errors.empty?
			#redirect_to post_path(@post)
		#else
			#render 'new'
		#end
	end

	def show
		#puts YAML::dump(params[:pamm])
		@fxtrends = Fxtrend.where("kind = 'month' AND pamm=?", params[:id])
		deposit = 100
		@arData = []
		@fxtrends.each do |el| 
			if el.percent.to_f > 0 
				el.percent = el.percent.to_f/2 			
			end
			deposit = deposit.to_f*(el.percent.to_f/100 + 1)
			deposit = deposit.round 2
			@arData << {date: el.date, deposit: deposit}		
		end
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_filter :find_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all				
	end

	# /posts/:id GET
	def show
		if @post
			render 'posts/show'
		else
			render text: 'Page not found', status: 404
		end
	end
	#def upvote
		
	#end

	# /posts/new GET
	def new
		@post = Post.new
	end

	# /posts/:id/edit GET
	def edit		
	end

	# /posts  POST
	def create
		@post = Post.new(params[:post])
		#puts YAML::dump("asdasdas")
		@post.save!
		#@post = Post.create(params[:post])

		if @post.errors.empty?
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	# /posts/:id PUT
	def update	
		@post.update_attributes(params[:post])		 
		if @post.errors.empty?
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	# /posts/:id DELETE
	def destroy		
		@post.destroy
		redirect_to action: 'index'
	end

	private
		def find_post
			@post = Post.where(id: params[:id]).first
			render_404 unless @post
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/fxtrends/index.html.erb
<h1>Pamms of Fx-trend</h1>


	<% @fxtrends.each do |fx| %>
	<div>
		<h2><%= link_to fx.pamm, fxtrend_path(fx) %></h2>
	<div><%= fx.pamm %></div>
		<%= link_to "Редактировать", edit_fxtrend_path(fx)  %>
		<%= link_to "Удалить", fx, method: :delete, data: {confirm:"Точно удалить?"} %>
	</div>

	<% end %>

app/views/fxtrends/new.html.erb
<h1>Add PAMM</h1>
<%= YAML::dump(@post) %>



<%= form_for @fxtrend, url: {action: 'create'} do |f| %>
	<%= f.text_field :pamm %> <br>
<p><%= f.submit "Создать", class: 'btn btn-success'%></p>
<% end %>

app/views/fxtrends/show.html.erb
	<link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">
	<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
	<script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>

	<div id="pammchart" style="height: 250px;"></div>
	<script>
		new Morris.Line({
		  // ID of the element in which to draw the chart.
		  element: 'pammchart',
		  // Chart data records -- each entry in this array corresponds to a point on
		  // the chart.
		  data: [
		  	<% @arData.each do |el| %>
		    { year: '<%=el[:date]%>', value: <%=el[:deposit]%> },
		    <% end%>	
		  ],
		  // The name of the data record attribute that contains x-values.
		  xkey: 'year',
		  // A list of names of data record attributes that contain y-values.
		  ykeys: ['value'],
		  // Labels for the ykeys -- will be displayed when you hover over the
		  // chart.
		  labels: ['deposit']
		});

	</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>	
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
</head>
<body>
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
    	<div class="container">
	      	<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      	</button>
	      	<a class="brand" href="/">Blog</a>
	      	<div class="nav-collapse collapse">
		        <ul class="nav">
		          <li class="active"><%= link_to "Add post", new_post_path(Post.new)  %></li>
		          <li><%= link_to "Fxtrends", fxtrends_path %></li>
		          <li><%= link_to "Add fxtrends", new_fxtrend_path(Fxtrend.new) %></li>
		          <li><a href="#contact">Contact</a></li>
		        </ul>
	      	</div><!--/.nav-collapse -->
    	</div>
  	</div>
</div>
<div class="container">
	<div class="row-fluid">
		<div class="span8">
			<%= yield %>
		</div>
		<div class="span4">
			Nunc non velit sit amet mauris dictum vehicula. Phasellus lacus libero, ultrices sit amet vehicula nec, suscipit sit amet ipsum. Curabitur convallis quam eget arcu ullamcorper in malesuada mauris hendrerit. Morbi convallis, erat sed consequat convallis, elit eros ultrices lacus, eget tempor metus purus vitae libero. Ut non quam turpis, eget gravida nibh. Donec vel tortor ligula. Sed dui neque, condimentum sit amet volutpat in, luctus eget leo.
		</div>
	</div>
</div>
</body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post,:html => {:class => "form-horizontal"} do |f| %>
	<fieldset>
		<legend>Редактировать запись</legend>
		<div class="control-group">
		 	<label class="control-label" for="title">Название</label>
		 	<div class="controls">
		 		<%= f.text_field :title, :class => "input-xlarge", id: "title" %>
			</div>
		</div>

		<!-- Textarea -->
		<div class="control-group">
			<label class="control-label" for="annot">Аннотация</label>
			<div class="controls">   
		 	<%= f.text_area :annot, id: "annot", :class => "span6", :rows=>5  %>
		  </div>
		</div>		
		<div class="control-group">
			<label class="control-label" for="description">Описание</label>
			<div class="controls">   
		 	<%= f.text_area :description, id: "description", :class => "span6", :rows=>5 %>
		  </div>
		</div>		
		<div class="control-group">
			<label class="control-label" for="enable">Включить</label>
			<div class="controls">   
		 	<%= f.check_box :enable, id: "enable" %>
		  </div>
		</div>		
		<div class="control-group">
			<div class="controls">   
		 	<%= f.submit "Редактировать", :class => "btn btn-success" %>
		  </div>
		</div>
	</fieldset>
<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>



	<% @posts.each do |p| %>
	<div>
		<h2><%= link_to p.title, post_path(p) %></h2>
	<div><%= p.annot %></div>
		<%= link_to "Редактировать", edit_post_path(p)  %>
		<%= link_to "Удалить", p, method: :delete, data: {confirm:"Точно удалить?"} %>
	</div>

	<% end %>

app/views/posts/new.html.erb
<%= form_for @post, url: {action: 'create'}, :html => {:class => "form-horizontal"} do |f| %>
	<fieldset>
		<legend>Добавит запись</legend>
		<div class="control-group">
		 	<label class="control-label" for="title">Название</label>
		 	<div class="controls">
		 		<%= f.text_field :title, :class => "input-xlarge", id: "title" %>
			</div>
		</div>

		<!-- Textarea -->
		<div class="control-group">
			<label class="control-label" for="annot">Аннотация</label>
			<div class="controls">   
		 	<%= f.text_area :annot, id: "annot", :class => "span6", :rows=>5  %>
		  </div>
		</div>		
		<div class="control-group">
			<label class="control-label" for="description">Описание</label>
			<div class="controls">   
		 	<%= f.text_area :description, id: "description", :class => "span6", :rows=>5 %>
		  </div>
		</div>		
		<div class="control-group">
			<label class="control-label" for="enable">Включить</label>
			<div class="controls">   
		 	<%= f.check_box :enable, id: "enable" %>
		  </div>
		</div>		
		<div class="control-group">
			<div class="controls">   
		 	<%= f.submit "Создать", :class => "btn btn-success" %>
		  </div>
		</div>
	</fieldset>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title%></h2>	
<p>Описание: <%= @post.description %></p>